# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile

FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci --only=production

# Copy built application
COPY dist/ ./dist/

# Create non-root user
RUN addgroup -g 1001 -S nodejs
RUN adduser -S gothink -u 1001

# Change ownership of the app directory
RUN chown -R gothink:nodejs /app
USER gothink

EXPOSE 3000

CMD ["node", "dist/server.js"]
